version: '3'

services:
  db:
    image: mysql:8.0.28
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fullcycle
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - dockernet

  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s npm start
    networks:
      - dockernet
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db
    
  nginx:
    build: 
      context: nginx
    container_name: nginx
    networks:
      - dockernet
    ports:
      - 8080:80

networks:
  dockernet:
    driver: bridge
